name = "scriba-tauri-update-server"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

routes = [
  { pattern = "https://update-server.scriba.metaloss.es", custom_domain = true }
]

[vars]
GITHUB_ACCOUNT = 'metalossAI'
GITHUB_REPO = 'NotarIA-UI'